INSERT INTO country (code, name, description, def, language_code) VALUES ('AD', 'ANDORRA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AE', 'UNITED ARAB EMIRATES (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AF', 'AFGHANISTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AG', 'ANTIGUA AND BARBUDA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AI', 'ANGUILLA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AL', 'ALBANIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AM', 'ARMENIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AN', 'NETHERLAND ANTILLES', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AO', 'ANGOLA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AQ', 'ANTARCTICA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AR', 'ARGENTINA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AS', 'AMERICAN SAMOA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AT', 'AUSTRIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AU', 'AUSTRALIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AW', 'ARUBA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AX', 'ALAND ISLANDS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('AZ', 'AZERBAIJAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BA', 'BOSNIA AND HERZEGOVINA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BB', 'BARBADOS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BD', 'BANGLADESH', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BE', 'BELGIUM', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BF', 'BURKINA FASO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BG', 'BULGARIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BH', 'BAHRAIN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BI', 'BURUNDI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BJ', 'BENIN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BL', 'SAINT BARTHELEMY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BM', 'BERMUDA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BN', 'BRUNEI DARUSSALAM', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BO', 'BOLIVIA (PLURINATIONAL STATE OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BQ', 'BONAIRE, SAINT EUSTATIUS AND SABA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BR', 'BRAZIL', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BS', 'BAHAMAS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BT', 'BHUTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BV', 'BOUVET ISLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BW', 'BOTSWANA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BY', 'BELARUS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('BZ', 'BELIZE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CA', 'CANADA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CC', 'COCOS (KEELING) ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CF', 'CENTRAL AFRICAN REPUBLIC (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CG', 'CONGO (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CH', 'SWITZERLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CI', 'COTE D''IVOIRE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CK', 'COOK ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CL', 'CHILE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CM', 'CAMEROON', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CN', 'CHINA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CO', 'COLOMBIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CR', 'COSTA RICA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CU', 'CUBA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CV', 'CAPE VERDE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CW', 'CURACAO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CX', 'CHRISTMAS ISLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CY', 'CYPRUS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('CZ', 'CZECH REPUBLIC (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('DE', 'GERMANY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('DJ', 'DJIBOUTI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('DK', 'DENMARK', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('DM', 'DOMINICA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('DO', 'DOMINICAN REPUBLIC (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('DZ', 'ALGERIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('EC', 'ECUADOR', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('EE', 'ESTONIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('EG', 'EGYPT', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('EH', 'WESTERN SAHARA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ER', 'ERITREA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ES', 'SPAIN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ET', 'ETHIOPIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('FI', 'FINLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('FJ', 'FIJI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('FK', 'FALKLAND ISLANDS (THE) [MALVINAS]', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('FM', 'MICRONESIA (FEDERATED STATES OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('FO', 'FAROE ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('FR', 'FRANCE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GA', 'GABON', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GB', 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GD', 'GRENADA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GE', 'GEORGIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GF', 'FRENCH GUIANA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GG', 'GUERNSEY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GH', 'GHANA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GI', 'GIBRALTAR', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GL', 'GREENLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GM', 'GAMBIA (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GN', 'GUINEA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GP', 'GUADELOUPE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GQ', 'EQUATORIAL GUINEA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GR', 'GREECE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GT', 'GUATEMALA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GU', 'GUAM', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GW', 'GUINEA-BISSAU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('GY', 'GUYANA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('HK', 'HONG KONG', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('HN', 'HONDURAS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('HR', 'CROATIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('HT', 'HAITI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('HU', 'HUNGARY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('id', 'INDONESIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IE', 'IRELAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IL', 'ISRAEL', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IM', 'ISLE OF MAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IN', 'INDIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IO', 'BRITISH INDIAN OCEAN TERRITORY (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IQ', 'IRAQ', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IR', 'IRAN (ISLAMIC REPUBLIC OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IS', 'ICELAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('IT', 'ITALY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('JE', 'JERSEY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('JM', 'JAMAICA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('JO', 'JORDAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('JP', 'JAPAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KE', 'KENYA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KG', 'KYRGYZSTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KH', 'CAMBODIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KI', 'KIRIBATI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KM', 'COMOROS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KN', 'SAINT KITTS AND NEVIS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KP', 'KOREA (DEMOCRATIC PEOPLE''S REPUBLIC OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KR', 'KOREA (REPUBLIC OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KW', 'KUWAIT', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KY', 'CAYMAN ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('KZ', 'KAZAKHSTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LB', 'LEBANON', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LC', 'SAINT LUCIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LI', 'LIECHTENSTEIN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LK', 'SRI LANKA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LR', 'LIBERIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LS', 'LESOTHO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LT', 'LITHUANIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LU', 'LUXEMBOURG', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LV', 'LATVIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('LY', 'LIBYAN ARAB JAMAHIRIYA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MA', 'MOROCCO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MC', 'MONACO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MD', 'MOLDOVA (REPUBLIC OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ME', 'MONTENEGRO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MF', 'SAINT MARTIN (FRENCH PART)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MG', 'MADAGASCAR', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MH', 'MARSHALL ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MK', 'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ML', 'MALI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MM', 'MYANMAR', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MN', 'MONGOLIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MO', 'MACAO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MP', 'NORTHERN MARIANA ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MQ', 'MARTINIQUE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MR', 'MAURITANIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MS', 'MONTSERRAT', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MT', 'MALTA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MU', 'MAURITIUS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MV', 'MALDIVES', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MW', 'MALAWI', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MX', 'MEXICO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MY', 'MALAYSIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('MZ', 'MOZAMBIQUE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NA', 'NAMIBIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NC', 'NEW CALEDONIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NE', 'NIGER (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NF', 'NORFOLK ISLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NG', 'NIGERIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NI', 'NICARAGUA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NL', 'NETHERLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NO', 'NORWAY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NP', 'NEPAL', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NR', 'NAURU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NU', 'NIUE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('NZ', 'NEW ZEALAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('OM', 'OMAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PA', 'PANAMA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PE', 'PERU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PF', 'FRENCH POLYNESIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PG', 'PAPUA NEW GUINEA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PH', 'PHILIPPINES (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PK', 'PAKISTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PL', 'POLAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PM', 'SAINT PIERRE AND MIQUELON', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PN', 'PITCAIRN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PR', 'PUERTO RICO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PT', 'PORTUGAL', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PW', 'PALAU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('PY', 'PARAGUAY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('QA', 'QATAR', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('RE', 'REUNION', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('RO', 'ROMANIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('RS', 'SERBIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('RU', 'RUSSIAN FEDERATION (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('RW', 'RWANDA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SA', 'SAUDI ARABIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SB', 'SOLOMON ISLANDS', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SC', 'SEYCHELLES', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SD', 'SUDAN (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SE', 'SWEDEN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SG', 'SINGAPORE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SI', 'SLOVENIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SJ', 'SVALBARD AND JAN MAYEN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SK', 'SLOVAKIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SL', 'SIERRA LEONE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SM', 'SAN MARINO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SN', 'SENEGAL', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SO', 'SOMALIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SR', 'SURIname', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SS', 'SOUTH SUDAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ST', 'SAO TOME AND PRINCIPE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SV', 'EL SALVADOR', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SX', 'SINT MAARTEN (DUTCH PART)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SY', 'SYRIAN ARAB REPUBLIC', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('SZ', 'SWAZILAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TC', 'TURKS AND CAICOS ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TD', 'CHAD', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TF', 'FRENCH SOUTHERN TERRITORIES (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TG', 'TOGO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TH', 'THAILAND', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TJ', 'TAJIKISTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TK', 'TOKELAU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TL', 'TIMOR-LESTE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TM', 'TURKMENISTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TN', 'TUNISIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TO', 'TONGA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TR', 'TURKEY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TT', 'TRINidAD AND TOBAGO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TV', 'TUVALU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TW', 'TAIWAN (PROVINCE OF CHINA)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('TZ', 'TANZANIA, UNITED REPUBLIC OF', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('UA', 'UKRAINE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('UG', 'UGANDA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('US', 'UNITED STATES OF AMERICA (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('UY', 'URUGUAY', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('UZ', 'UZBEKISTAN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VA', 'HOLY SEE (THE)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VC', 'SAINT VINCENT AND THE GRENADINES', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VE', 'VENEZUELA (BOLIVARIAN REPUBLIC OF)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VG', 'VIRGIN ISLANDS (BRITISH)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VI', 'VIRGIN ISLANDS (U.S.)', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VN', 'VIET NAM', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('VU', 'VANUATU', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('WF', 'WALLIS AND FUTUNA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('WS', 'SAMOA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('XK', 'KOSOVO', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('YE', 'YEMEN', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('YT', 'MAYOTTE', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ZA', 'SOUTH AFRICA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ZM', 'ZAMBIA', '', false, 'en');
INSERT INTO country (code, name, description, def, language_code) VALUES ('ZW', 'ZIMBABWE', '', false, 'en');
