spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mdmdb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true


eureka:
  client:
    enabled: false

health:
  config:
    enabled: false

management:
  health:
    #    diskspace:
    #      enabled: true
    db:
      enabled: true
    #    refresh:
    #      enabled: false
    defaults:
      enabled: false

  endpoint:
    health:
      show-details: always

  #    loggers:
  #      enabled: true

  endpoints:
    web:
      exposure:
        include: "health,prometheus"

#    jmx:
#      domain: com.procurement
#      exposure:
#        exclude: "*"

#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#      sla:
#        http:
#          server:
#            requests: 1ms,5ms
#  server:
#    port: 9999
#  info:
#    git:
#      mode: full