spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.20.112:5432/mdm
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      pool-name: mdm-pool
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
